Added description of the examples in the READMEs.
xenserver/xenserver-samples pull request #9
Opened 2023-08-22 01:43 UTC by kc284

This is info that I'm removing from the SDK guide. It's easier to manage if it's closer where the example code actually resides.

2023-08-24 07:08 UTC, danilo-delbusso requested changes

2023-08-24 07:08 UTC, danilo-delbusso commented on c/README.md
> +-  `test_vm_async_migrate`: Shows how to use asynchronous API calls to migrate
nit: language to use coordinator/supporter? I know we're not consistent but we can address this one?

2023-08-24 07:08 UTC, danilo-delbusso commented on csharp/README.md
> +-  `GetVariousRecords`: logs to a XenServer host and displays information about
nit: logs in*
 
 VERY nit: start the bullet points with capital letters like in other READMEs? (same in the python readme)


same below

2023-08-26 13:26 UTC, danilo-delbusso approved these changes
<img src='https://emojis.slackmojis.com/emojis/images/1643514065/210/yay.gif?1643514065' height='30' /> <img src='https://emojis.slackmojis.com/emojis/images/1643515474/14957/meow_checkmark.png?1643515474' height='30' />

2023-10-23 08:59 UTC, CitrixChris approved these changes

2023-10-23 10:02 UTC, merged